services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  producer:
    depends_on:
      - rabbitmq
    container_name: rabbitmq-producer
    image: ghcr.io/szomelioza/rabbitmq-random-producer:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=test
      - SENT_MSG_LIMIT=100
      - MIN_SLEEP=0
      - MAX_SLEEP=3
  consumer:
    depends_on:
      - rabbitmq
    container_name: rabbitmq-consumer
    image: ghcr.io/szomelioza/rabbitmq-random-consumer:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=test
      - MIN_SLEEP=5
      - MAX_SLEEP=6
