services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  producer:
    depends_on:
      - rabbitmq
    container_name: rabbitmq-producer
    build:
      context: .
      dockerfile: producer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=test
      - MIN_SLEEP=0
      - MAX_SLEEP=3
      - MSG_LIMIT=1000
  consumer:
    depends_on:
      - rabbitmq
    container_name: rabbitmq-consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=test
      - MIN_SLEEP=5
      - MAX_SLEEP=6
