services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  producer:
    depends_on:
      - rabbitmq
    container_name: rabbitmq-producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - QUEUE_NAME=test
      - SENT_MSG_LIMIT=10
